consumes:
  - application/json
produces:
  - application/json
info:
  description: gobox
  title: gobox
  version: "2.0"
schemes:
  - http
swagger: "2.0"

definitions:
  SignUpReq:
    type: object
    required:
      - username
      - password
      - email
      - email_code
    properties:
      username:
        type: string
        format: string
        description: Ваше никнейм
        minLength: 6
      password:
        type: string
        format: string
        description: Ваш пароль
        minLength: 6
      email:
        type: string
        format: email
        description: Ваша электоронная почта
        example: email@gmail.com
      email_code:
        type: integer
        format: int64
        description: Код который пришел вам на почту
        minLength: 6
        maxLength: 6
        example: 123456
  SignInReq:
    type: object
    required:
      - username
      - password
    properties:
      username:
        type: string
        format: string
        description: Ваше никнейм
        minLength: 6
      password:
        type: string
        format: string
        description: Ваш пароль
        minLength: 6
  SignInRes:
    type: object
    required:
      - accessToken
    properties:
      accessToken:
        type: string
        format: string
        description: Токен доступа, токен обновления будет лежать в заголовках (куках)      

paths:
  /sign-up:
    post:
      tags:
        - auth
      summary: sign-up
      description: Эндпоинт, который предназначен для регистрации нового пользователя
      operationId: sign_up
      parameters:
        - name: sign_up
          in: body
          required: true
          schema:
            $ref: "#/definitions/SignUpReq"
      responses:
        200:
          description: Вы зарагестрировались
        400:
          description: Данные неверные 
        500:
          description: Ошибка сервера
        default:
          description: Ошибка

  /sign-in:
    post:
      tags:
        - auth
      summary: sign-in
      description: При запросе на этот эндпоинт произойдет отправка пароля и логина, также в куки будет положен отпечаток браузера (x-request-id) и токен обновления (httpOnly)
      operationId: sign_in
      parameters:
        - name: sign_in
          in: body
          required: true
          schema:
            $ref: "#/definitions/SignInReq"
      responses:
        200:
          description: Вы вошли
          schema:
            $ref: "#/definitions/SignInRes"
        400:
          description: Данные неверные 
        500:
          description: Ошибка сервера
        default:
          description: Ошибка

  /sign-out:
    post:
      tags:
        - auth
      summary: sign-out
      description: Фингерпринт и токен обновления будут удалены, а токен доступа должен быть удален на клиенте
      operationId: sign_out
      parameters:
        - name: refreshToken
          in: header
          description: Токен обновления
          required: false
          type: string
        - name: fingerprint
          in: header
          description: Уникальный отпечаток в x-request-id
          required: false
          type: string
      responses:
        200:
          description: Вы разлогинились
        500:
          description: Ошибка сервера
        default:
          description: Ошибка

  /sign-refresh:
    post:
      tags:
        - auth
      summary: sign-refresh
      description: При запросе токен обновления и токен доступа будут обновлены
      operationId: sign_refresh
      parameters:
        - name: refreshToken
          in: header
          description: Токен обновления
          required: true
          type: string
        - name: fingerprint
          in: header
          description: Уникальный отпечаток в x-request-id
          required: true
          type: string
      responses:
        200:
          description: Токены обновились
          schema:
            $ref: "#/definitions/SignInRes"
        500:
          description: Ошибка сервера
        default:
          description: Ошибка
       