// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SignOutHandlerFunc turns a function with the right signature into a sign out handler
type SignOutHandlerFunc func(SignOutParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SignOutHandlerFunc) Handle(params SignOutParams) middleware.Responder {
	return fn(params)
}

// SignOutHandler interface for that can handle valid sign out params
type SignOutHandler interface {
	Handle(SignOutParams) middleware.Responder
}

// NewSignOut creates a new http.Handler for the sign out operation
func NewSignOut(ctx *middleware.Context, handler SignOutHandler) *SignOut {
	return &SignOut{Context: ctx, Handler: handler}
}

/*
	SignOut swagger:route POST /sign-out auth signOut

sign-out

Фингерпринт и токен обновления будут удалены, а токен доступа должен быть удален на клиенте
*/
type SignOut struct {
	Context *middleware.Context
	Handler SignOutHandler
}

func (o *SignOut) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSignOutParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
