// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"swg/models"
)

// SignInOKCode is the HTTP code returned for type SignInOK
const SignInOKCode int = 200

/*
SignInOK Вы вошли

swagger:response signInOK
*/
type SignInOK struct {

	/*
	  In: Body
	*/
	Payload *models.SignInRes `json:"body,omitempty"`
}

// NewSignInOK creates SignInOK with default headers values
func NewSignInOK() *SignInOK {

	return &SignInOK{}
}

// WithPayload adds the payload to the sign in o k response
func (o *SignInOK) WithPayload(payload *models.SignInRes) *SignInOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the sign in o k response
func (o *SignInOK) SetPayload(payload *models.SignInRes) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SignInOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// SignInBadRequestCode is the HTTP code returned for type SignInBadRequest
const SignInBadRequestCode int = 400

/*
SignInBadRequest Данные неверные

swagger:response signInBadRequest
*/
type SignInBadRequest struct {
}

// NewSignInBadRequest creates SignInBadRequest with default headers values
func NewSignInBadRequest() *SignInBadRequest {

	return &SignInBadRequest{}
}

// WriteResponse to the client
func (o *SignInBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// SignInInternalServerErrorCode is the HTTP code returned for type SignInInternalServerError
const SignInInternalServerErrorCode int = 500

/*
SignInInternalServerError Ошибка сервера

swagger:response signInInternalServerError
*/
type SignInInternalServerError struct {
}

// NewSignInInternalServerError creates SignInInternalServerError with default headers values
func NewSignInInternalServerError() *SignInInternalServerError {

	return &SignInInternalServerError{}
}

// WriteResponse to the client
func (o *SignInInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

/*
SignInDefault Ошибка

swagger:response signInDefault
*/
type SignInDefault struct {
	_statusCode int
}

// NewSignInDefault creates SignInDefault with default headers values
func NewSignInDefault(code int) *SignInDefault {
	if code <= 0 {
		code = 500
	}

	return &SignInDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the sign in default response
func (o *SignInDefault) WithStatusCode(code int) *SignInDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the sign in default response
func (o *SignInDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *SignInDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
