// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// SignUpOKCode is the HTTP code returned for type SignUpOK
const SignUpOKCode int = 200

/*
SignUpOK Вы зарагестрировались

swagger:response signUpOK
*/
type SignUpOK struct {
}

// NewSignUpOK creates SignUpOK with default headers values
func NewSignUpOK() *SignUpOK {

	return &SignUpOK{}
}

// WriteResponse to the client
func (o *SignUpOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// SignUpBadRequestCode is the HTTP code returned for type SignUpBadRequest
const SignUpBadRequestCode int = 400

/*
SignUpBadRequest Данные неверные

swagger:response signUpBadRequest
*/
type SignUpBadRequest struct {
}

// NewSignUpBadRequest creates SignUpBadRequest with default headers values
func NewSignUpBadRequest() *SignUpBadRequest {

	return &SignUpBadRequest{}
}

// WriteResponse to the client
func (o *SignUpBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// SignUpInternalServerErrorCode is the HTTP code returned for type SignUpInternalServerError
const SignUpInternalServerErrorCode int = 500

/*
SignUpInternalServerError Ошибка сервера

swagger:response signUpInternalServerError
*/
type SignUpInternalServerError struct {
}

// NewSignUpInternalServerError creates SignUpInternalServerError with default headers values
func NewSignUpInternalServerError() *SignUpInternalServerError {

	return &SignUpInternalServerError{}
}

// WriteResponse to the client
func (o *SignUpInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

/*
SignUpDefault Ошибка

swagger:response signUpDefault
*/
type SignUpDefault struct {
	_statusCode int
}

// NewSignUpDefault creates SignUpDefault with default headers values
func NewSignUpDefault(code int) *SignUpDefault {
	if code <= 0 {
		code = 500
	}

	return &SignUpDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the sign up default response
func (o *SignUpDefault) WithStatusCode(code int) *SignUpDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the sign up default response
func (o *SignUpDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *SignUpDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
