// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SignRefreshHandlerFunc turns a function with the right signature into a sign refresh handler
type SignRefreshHandlerFunc func(SignRefreshParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SignRefreshHandlerFunc) Handle(params SignRefreshParams) middleware.Responder {
	return fn(params)
}

// SignRefreshHandler interface for that can handle valid sign refresh params
type SignRefreshHandler interface {
	Handle(SignRefreshParams) middleware.Responder
}

// NewSignRefresh creates a new http.Handler for the sign refresh operation
func NewSignRefresh(ctx *middleware.Context, handler SignRefreshHandler) *SignRefresh {
	return &SignRefresh{Context: ctx, Handler: handler}
}

/*
	SignRefresh swagger:route POST /sign-refresh auth signRefresh

sign-refresh

При запросе токен обновления и токен доступа будут обновлены
*/
type SignRefresh struct {
	Context *middleware.Context
	Handler SignRefreshHandler
}

func (o *SignRefresh) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSignRefreshParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
