// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// SignUpHandlerFunc turns a function with the right signature into a sign up handler
type SignUpHandlerFunc func(SignUpParams) middleware.Responder

// Handle executing the request and returning a response
func (fn SignUpHandlerFunc) Handle(params SignUpParams) middleware.Responder {
	return fn(params)
}

// SignUpHandler interface for that can handle valid sign up params
type SignUpHandler interface {
	Handle(SignUpParams) middleware.Responder
}

// NewSignUp creates a new http.Handler for the sign up operation
func NewSignUp(ctx *middleware.Context, handler SignUpHandler) *SignUp {
	return &SignUp{Context: ctx, Handler: handler}
}

/*
	SignUp swagger:route POST /sign-up auth signUp

sign-up

Эндпоинт, который предназначен для регистрации нового пользователя
*/
type SignUp struct {
	Context *middleware.Context
	Handler SignUpHandler
}

func (o *SignUp) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewSignUpParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
