// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// SignOutOKCode is the HTTP code returned for type SignOutOK
const SignOutOKCode int = 200

/*
SignOutOK Вы разлогинились

swagger:response signOutOK
*/
type SignOutOK struct {
}

// NewSignOutOK creates SignOutOK with default headers values
func NewSignOutOK() *SignOutOK {

	return &SignOutOK{}
}

// WriteResponse to the client
func (o *SignOutOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// SignOutInternalServerErrorCode is the HTTP code returned for type SignOutInternalServerError
const SignOutInternalServerErrorCode int = 500

/*
SignOutInternalServerError Ошибка сервера

swagger:response signOutInternalServerError
*/
type SignOutInternalServerError struct {
}

// NewSignOutInternalServerError creates SignOutInternalServerError with default headers values
func NewSignOutInternalServerError() *SignOutInternalServerError {

	return &SignOutInternalServerError{}
}

// WriteResponse to the client
func (o *SignOutInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}

/*
SignOutDefault Ошибка

swagger:response signOutDefault
*/
type SignOutDefault struct {
	_statusCode int
}

// NewSignOutDefault creates SignOutDefault with default headers values
func NewSignOutDefault(code int) *SignOutDefault {
	if code <= 0 {
		code = 500
	}

	return &SignOutDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the sign out default response
func (o *SignOutDefault) WithStatusCode(code int) *SignOutDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the sign out default response
func (o *SignOutDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *SignOutDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
