// Code generated by go-swagger; DO NOT EDIT.

// Package restapi gobox
//
//	gobox
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 2.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
