// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "gobox",
    "title": "gobox",
    "version": "2.0"
  },
  "paths": {
    "/sign-in": {
      "post": {
        "description": "При запросе на этот эндпоинт произойдет отправка пароля и логина, также в куки будет положен отпечаток браузера (x-request-id) и токен обновления (httpOnly)",
        "tags": [
          "auth"
        ],
        "summary": "sign-in",
        "operationId": "sign_in",
        "parameters": [
          {
            "name": "sign_in",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/SignInReq"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Вы вошли",
            "schema": {
              "$ref": "#/definitions/SignInRes"
            }
          },
          "400": {
            "description": "Данные неверные"
          },
          "500": {
            "description": "Ошибка сервера"
          },
          "default": {
            "description": "Ошибка"
          }
        }
      }
    },
    "/sign-out": {
      "post": {
        "description": "Фингерпринт и токен обновления будут удалены, а токен доступа должен быть удален на клиенте",
        "tags": [
          "auth"
        ],
        "summary": "sign-out",
        "operationId": "sign_out",
        "parameters": [
          {
            "type": "string",
            "description": "Токен обновления",
            "name": "refreshToken",
            "in": "header"
          },
          {
            "type": "string",
            "description": "Уникальный отпечаток в x-request-id",
            "name": "fingerprint",
            "in": "header"
          }
        ],
        "responses": {
          "200": {
            "description": "Вы разлогинились"
          },
          "500": {
            "description": "Ошибка сервера"
          },
          "default": {
            "description": "Ошибка"
          }
        }
      }
    },
    "/sign-refresh": {
      "post": {
        "description": "При запросе токен обновления и токен доступа будут обновлены",
        "tags": [
          "auth"
        ],
        "summary": "sign-refresh",
        "operationId": "sign_refresh",
        "parameters": [
          {
            "type": "string",
            "description": "Токен обновления",
            "name": "refreshToken",
            "in": "header",
            "required": true
          },
          {
            "type": "string",
            "description": "Уникальный отпечаток в x-request-id",
            "name": "fingerprint",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Токены обновились",
            "schema": {
              "$ref": "#/definitions/SignInRes"
            }
          },
          "500": {
            "description": "Ошибка сервера"
          },
          "default": {
            "description": "Ошибка"
          }
        }
      }
    },
    "/sign-up": {
      "post": {
        "description": "Эндпоинт, который предназначен для регистрации нового пользователя",
        "tags": [
          "auth"
        ],
        "summary": "sign-up",
        "operationId": "sign_up",
        "parameters": [
          {
            "name": "sign_up",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/SignUpReq"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Вы зарагестрировались"
          },
          "400": {
            "description": "Данные неверные"
          },
          "500": {
            "description": "Ошибка сервера"
          },
          "default": {
            "description": "Ошибка"
          }
        }
      }
    }
  },
  "definitions": {
    "SignInReq": {
      "type": "object",
      "required": [
        "username",
        "password"
      ],
      "properties": {
        "password": {
          "description": "Ваш пароль",
          "type": "string",
          "format": "string",
          "minLength": 6
        },
        "username": {
          "description": "Ваше никнейм",
          "type": "string",
          "format": "string",
          "minLength": 6
        }
      }
    },
    "SignInRes": {
      "type": "object",
      "required": [
        "accessToken"
      ],
      "properties": {
        "accessToken": {
          "description": "Токен доступа, токен обновления будет лежать в заголовках (куках)",
          "type": "string",
          "format": "string"
        }
      }
    },
    "SignUpReq": {
      "type": "object",
      "required": [
        "username",
        "password",
        "email",
        "email_code"
      ],
      "properties": {
        "email": {
          "description": "Ваша электоронная почта",
          "type": "string",
          "format": "email",
          "example": "email@gmail.com"
        },
        "email_code": {
          "description": "Код который пришел вам на почту",
          "type": "integer",
          "format": "int64",
          "maxLength": 6,
          "minLength": 6,
          "example": 123456
        },
        "password": {
          "description": "Ваш пароль",
          "type": "string",
          "format": "string",
          "minLength": 6
        },
        "username": {
          "description": "Ваше никнейм",
          "type": "string",
          "format": "string",
          "minLength": 6
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "gobox",
    "title": "gobox",
    "version": "2.0"
  },
  "paths": {
    "/sign-in": {
      "post": {
        "description": "При запросе на этот эндпоинт произойдет отправка пароля и логина, также в куки будет положен отпечаток браузера (x-request-id) и токен обновления (httpOnly)",
        "tags": [
          "auth"
        ],
        "summary": "sign-in",
        "operationId": "sign_in",
        "parameters": [
          {
            "name": "sign_in",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/SignInReq"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Вы вошли",
            "schema": {
              "$ref": "#/definitions/SignInRes"
            }
          },
          "400": {
            "description": "Данные неверные"
          },
          "500": {
            "description": "Ошибка сервера"
          },
          "default": {
            "description": "Ошибка"
          }
        }
      }
    },
    "/sign-out": {
      "post": {
        "description": "Фингерпринт и токен обновления будут удалены, а токен доступа должен быть удален на клиенте",
        "tags": [
          "auth"
        ],
        "summary": "sign-out",
        "operationId": "sign_out",
        "parameters": [
          {
            "type": "string",
            "description": "Токен обновления",
            "name": "refreshToken",
            "in": "header"
          },
          {
            "type": "string",
            "description": "Уникальный отпечаток в x-request-id",
            "name": "fingerprint",
            "in": "header"
          }
        ],
        "responses": {
          "200": {
            "description": "Вы разлогинились"
          },
          "500": {
            "description": "Ошибка сервера"
          },
          "default": {
            "description": "Ошибка"
          }
        }
      }
    },
    "/sign-refresh": {
      "post": {
        "description": "При запросе токен обновления и токен доступа будут обновлены",
        "tags": [
          "auth"
        ],
        "summary": "sign-refresh",
        "operationId": "sign_refresh",
        "parameters": [
          {
            "type": "string",
            "description": "Токен обновления",
            "name": "refreshToken",
            "in": "header",
            "required": true
          },
          {
            "type": "string",
            "description": "Уникальный отпечаток в x-request-id",
            "name": "fingerprint",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Токены обновились",
            "schema": {
              "$ref": "#/definitions/SignInRes"
            }
          },
          "500": {
            "description": "Ошибка сервера"
          },
          "default": {
            "description": "Ошибка"
          }
        }
      }
    },
    "/sign-up": {
      "post": {
        "description": "Эндпоинт, который предназначен для регистрации нового пользователя",
        "tags": [
          "auth"
        ],
        "summary": "sign-up",
        "operationId": "sign_up",
        "parameters": [
          {
            "name": "sign_up",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/SignUpReq"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Вы зарагестрировались"
          },
          "400": {
            "description": "Данные неверные"
          },
          "500": {
            "description": "Ошибка сервера"
          },
          "default": {
            "description": "Ошибка"
          }
        }
      }
    }
  },
  "definitions": {
    "SignInReq": {
      "type": "object",
      "required": [
        "username",
        "password"
      ],
      "properties": {
        "password": {
          "description": "Ваш пароль",
          "type": "string",
          "format": "string",
          "minLength": 6
        },
        "username": {
          "description": "Ваше никнейм",
          "type": "string",
          "format": "string",
          "minLength": 6
        }
      }
    },
    "SignInRes": {
      "type": "object",
      "required": [
        "accessToken"
      ],
      "properties": {
        "accessToken": {
          "description": "Токен доступа, токен обновления будет лежать в заголовках (куках)",
          "type": "string",
          "format": "string"
        }
      }
    },
    "SignUpReq": {
      "type": "object",
      "required": [
        "username",
        "password",
        "email",
        "email_code"
      ],
      "properties": {
        "email": {
          "description": "Ваша электоронная почта",
          "type": "string",
          "format": "email",
          "example": "email@gmail.com"
        },
        "email_code": {
          "description": "Код который пришел вам на почту",
          "type": "integer",
          "format": "int64",
          "maxLength": 6,
          "minLength": 6,
          "example": 123456
        },
        "password": {
          "description": "Ваш пароль",
          "type": "string",
          "format": "string",
          "minLength": 6
        },
        "username": {
          "description": "Ваше никнейм",
          "type": "string",
          "format": "string",
          "minLength": 6
        }
      }
    }
  }
}`))
}
