version: "3"

networks:
  postgres:
    driver: bridge
volumes:
  init: 
  data: 

services:
  postgres:
    container_name: my_db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 1s
    ports:
      - "5431:5432" # почему то он хочет, чтобы в pgadmin port = 5432
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
      # - type: bind
        # source: ./init
        # target: /docker-entrypoint-initdb.d
        # target: /home/init.sh
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"