version: '3.9'

services:
  db:
    container_name: pg
    image: postgres:14
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    # volumes:
    #   - ./posrgres_data:/var/lib/posrgresql/data
  
  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: root
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - "5050:80"