// Code generated by MockGen. DO NOT EDIT.
// Source: api.go

// Package mock_handlers is a generated GoMock package.
package mock_handlers

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	echo "github.com/labstack/echo/v4"
)

// MockIHandlers is a mock of IHandlers interface.
type MockIHandlers struct {
	ctrl     *gomock.Controller
	recorder *MockIHandlersMockRecorder
}

// MockIHandlersMockRecorder is the mock recorder for MockIHandlers.
type MockIHandlersMockRecorder struct {
	mock *MockIHandlers
}

// NewMockIHandlers creates a new mock instance.
func NewMockIHandlers(ctrl *gomock.Controller) *MockIHandlers {
	mock := &MockIHandlers{ctrl: ctrl}
	mock.recorder = &MockIHandlersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIHandlers) EXPECT() *MockIHandlersMockRecorder {
	return m.recorder
}

// ApiGetAppData mocks base method.
func (m *MockIHandlers) ApiGetAppData(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApiGetAppData", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApiGetAppData indicates an expected call of ApiGetAppData.
func (mr *MockIHandlersMockRecorder) ApiGetAppData(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApiGetAppData", reflect.TypeOf((*MockIHandlers)(nil).ApiGetAppData), c)
}

// ApiSaveAppData mocks base method.
func (m *MockIHandlers) ApiSaveAppData(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApiSaveAppData", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApiSaveAppData indicates an expected call of ApiSaveAppData.
func (mr *MockIHandlersMockRecorder) ApiSaveAppData(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApiSaveAppData", reflect.TypeOf((*MockIHandlers)(nil).ApiSaveAppData), c)
}

// AuthRefresh mocks base method.
func (m *MockIHandlers) AuthRefresh(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthRefresh", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// AuthRefresh indicates an expected call of AuthRefresh.
func (mr *MockIHandlersMockRecorder) AuthRefresh(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthRefresh", reflect.TypeOf((*MockIHandlers)(nil).AuthRefresh), c)
}

// AuthSignIn mocks base method.
func (m *MockIHandlers) AuthSignIn(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthSignIn", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// AuthSignIn indicates an expected call of AuthSignIn.
func (mr *MockIHandlersMockRecorder) AuthSignIn(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthSignIn", reflect.TypeOf((*MockIHandlers)(nil).AuthSignIn), c)
}

// AuthSignOut mocks base method.
func (m *MockIHandlers) AuthSignOut(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthSignOut", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// AuthSignOut indicates an expected call of AuthSignOut.
func (mr *MockIHandlersMockRecorder) AuthSignOut(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthSignOut", reflect.TypeOf((*MockIHandlers)(nil).AuthSignOut), c)
}

// AuthSignUp mocks base method.
func (m *MockIHandlers) AuthSignUp(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthSignUp", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// AuthSignUp indicates an expected call of AuthSignUp.
func (mr *MockIHandlersMockRecorder) AuthSignUp(c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthSignUp", reflect.TypeOf((*MockIHandlers)(nil).AuthSignUp), c)
}
