// Code generated by MockGen. DO NOT EDIT.
// Source: api.go

// Package mock_services is a generated GoMock package.
package mock_services

import (
	models "jwt/pkg/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// GiveAppTokens mocks base method.
func (m *MockIService) GiveAppTokens(username string) ([]models.AppToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GiveAppTokens", username)
	ret0, _ := ret[0].([]models.AppToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GiveAppTokens indicates an expected call of GiveAppTokens.
func (mr *MockIServiceMockRecorder) GiveAppTokens(username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GiveAppTokens", reflect.TypeOf((*MockIService)(nil).GiveAppTokens), username)
}

// Refresh mocks base method.
func (m *MockIService) Refresh(refreshToken string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", refreshToken)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Refresh indicates an expected call of Refresh.
func (mr *MockIServiceMockRecorder) Refresh(refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockIService)(nil).Refresh), refreshToken)
}

// SaveAppTokens mocks base method.
func (m *MockIService) SaveAppTokens(useraname string, appTokens []models.AppToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAppTokens", useraname, appTokens)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAppTokens indicates an expected call of SaveAppTokens.
func (mr *MockIServiceMockRecorder) SaveAppTokens(useraname, appTokens interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAppTokens", reflect.TypeOf((*MockIService)(nil).SaveAppTokens), useraname, appTokens)
}

// SignIn mocks base method.
func (m *MockIService) SignIn(arg0 models.SignIn) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignIn", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignIn indicates an expected call of SignIn.
func (mr *MockIServiceMockRecorder) SignIn(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignIn", reflect.TypeOf((*MockIService)(nil).SignIn), arg0)
}

// SignUp mocks base method.
func (m *MockIService) SignUp(username, password, email string, emailCode int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUp", username, password, email, emailCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignUp indicates an expected call of SignUp.
func (mr *MockIServiceMockRecorder) SignUp(username, password, email, emailCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUp", reflect.TypeOf((*MockIService)(nil).SignUp), username, password, email, emailCode)
}
